version: '3.1'

volumes:
  mariadb:
    driver: local

networks:
  db:
    driver: bridge

services:
  mariadb:
    container_name: db
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    expose:
      - "40000:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init-script.sql
      - mariadb:/var/lib/mysql
    networks:
      db:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - UPLOAD_LIMIT=560123000456
    networks:
      db:
  verifier:
    depends_on:
      - mariadb
    image: verifier:latest
    restart: always
    expose:
      - "40002"
    ports:
      - "40002:80"
    environment:
      - DB_URL=root:123456@tcp(db:3306)/verifier
      - DISCORD_GUILD=server_id
      - DISCORD_TOKEN=token
      - SECRET=random_secret_password
    networks:
      db: