name: Staticcheck

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:

  staticcheck:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        go: [ "1.20.x" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: "go vet ./..."
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.2"
          cache-key: ${{ matrix.go }}
